update therapeutic inertia
ihmeuw/vivarium_nih_us_cvd pull request #139
Opened 2023-07-18 21:27 UTC by hussain-jafari

## update therapeutic inertia

### Description
- *Category*: feature
- *JIRA issue*: [MIC-4229](https://jira.ihme.washington.edu/browse/MIC-4229)
- *Research reference*: [SBP Treatment Ramp](https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_us_cvd/concept_model.html#healthcare-system-modeling)

### Changes and notes
Update therapeutic inertia to be constant when initially prescribing blood pressure medication.  

### Verification and Testing
Used a breakpoint to define custom measured SBP values and verified that indexes were being defined properly.

2023-07-18 21:52 UTC, stevebachmeier approved these changes

2023-07-19 16:24 UTC, rmudambi requested changes

2023-07-19 16:24 UTC, rmudambi commented on src/vivarium_nih_us_cvd/components/treatment.py
>          overcome_therapeutic_inertia = pop_visitors[
This should be removed?

2023-07-19 16:24 UTC, rmudambi commented on src/vivarium_nih_us_cvd/components/treatment.py
> +            overcome_therapeutic_inertia.difference(currently_medicated)
You're referencing the wrong therapeutic inertia variable here  (i.e. the one that should have been removed).

2023-07-19 16:27 UTC, hussain-jafari commented on src/vivarium_nih_us_cvd/components/treatment.py
> +            overcome_therapeutic_inertia.difference(currently_medicated)
We still want to redraw inertia every time someone visits the doctor if they are changing medication or have medium SBP and are being prescribed medication for the first time. We want to keep inertia constant when determining if someone with high SBP is being prescribed medication for the first time.

2023-07-19 17:55 UTC, rmudambi approved these changes

2023-07-19 18:01 UTC, merged