Heart failure RRs
ihmeuw/vivarium_nih_us_cvd pull request #99
Opened 2023-03-30 21:38 UTC by hussain-jafari

## Heart failure RRs 

### Changes and notes
No new or unapproved changes, merging components necessary for risk effects on heart failure.

2023-03-30 22:42 UTC, rmudambi requested changes

2023-03-30 22:42 UTC, rmudambi commented on src/vivarium_nih_us_cvd/components/__init__.py
> -    CategoricalColumnObserver,
This will break running our normal non-paf-calculating simulations.

2023-03-31 14:50 UTC, hussain-jafari commented on src/vivarium_nih_us_cvd/components/__init__.py
> -    CategoricalColumnObserver,
Updated and ran for a few time steps.

2023-03-31 17:55 UTC, rmudambi approved these changes

2023-03-31 18:07 UTC, merged